### ISSUE TITLE
Add examples folder to demonstrate full Veracruz use cases 

### ISSUE THREAD

**Issue by basmaelgaabouri** [veracruz-project/veracruz#22] opened 2020-10-30 12:17 UTC
Create an examples folder where each example shows how to put all components together (program owner, data owner, policy, wasm binary ..), maybe examples can be driving by different Veracruz use cases.

**Comment by dominic-mulligan-arm** [comment] 2020-10-30 12:22
I think this is a good idea.  At the moment we have:

- examples of how you write a program for Veracruz under `sdk/examples`,
- full-system integration tests under `sinaloa-test` and `veracruz-test` which are not written in an especially-clear way (see also #3, which I think is closely related to this) and fetch their required bits-and-pieces from all over the place in the repository (e.g. the policies, WASM binary, etc.)

...but no directory that collects a few simple examples together, with WASM program, policy, client code, scripts for deploying a Veracruz isolate, etc. all in one place to get newcomers going with the project.  Moreover, some of these examples could be tied to some of the use-cases that we discuss in the `README` file, which would be a nice tie-in.

**Comment by dreemkiller** [comment] 2020-10-30 13:30
This might be a duplicate of #3

**Comment by dominic-mulligan-arm** [comment] 2020-10-30 13:40
I wasn't sure at first whether this was an exact duplicate of #3, but I think you are right.  I'll mark this as a duplicate and close.

**Closed by dominic-mulligan-arm** 2020-10-30 13:40 UTC
Labels: documentation, enhancement, help wanted
