### ISSUE TITLE
Add support for MCU clients

### ISSUE THREAD

**Issue by dreemkiller** [veracruz-project/veracruz#41] opened 2020-11-10 16:32 UTC
**Requested feature**
Add support for MCU clients with minimal resources running on a Cortex-M class device

**Motivation**
Currently, the client library is written without constrained devices in mind, so it is not optimized for size and performance.
We see use-cases where low end Cortex-M devices running an embedded RTOS would like to offload computation without having to trust the owner of the device being offloaded to.

**Additional context**
We currently use RustLS, which is not optimized for low end devices. Should probably use MbedTLS as the TLS library.

**Comment by dominic-mulligan-arm** [comment] 2020-11-10 16:34
Is this a duplicate of #9?  Actually, this has more information in it, so if you agree that there's a duplication then I will close #9.

**Closed** 2021-08-12 22:53 UTC
Labels: enhancement, client-code
