### ISSUE TITLE
Experiment with micro-controller support for Veracruz

### ISSUE THREAD

**Issue by dominic-mulligan-arm** [veracruz-project/veracruz#9] opened 2020-10-27 17:31 UTC
At the moment Veracruz client code (Durango) is designed and built for use on an application-class microprocessor (e.g. an Arm A-core).  However, there are potential use-cases where microcontrollers could "talk" directly to the trusted Veracruz runtime.  To support this, we need:

1. Some compelling use-cases to act as guides for implementation.
2. A version of Durango that is usable on a resource-constrained device.
3. Additional examples, tied to the use-cases highlighted above.

**Comment by dreemkiller** [comment] 2020-11-10 16:36
Duplicate of #41 (which has more info)

**Closed by dreemkiller** 2020-11-10 16:36 UTC
Labels: client-code, enhancement
